### ISSUE TITLE
Digits not aligned

### ISSUE THREAD

**Issue by leecasey** [mingsnx/animated_digit#6]
<img width="188" alt="Screenshot 2022-05-23 at 08 42 18" src="https://user-images.githubusercontent.com/7038045/183021196-073c4340-ce0c-402a-9732-03ffb3b7d410.png">
Any idea why this is happening guys?

**Comment by leecasey** [comment]
`AnimatedDigitWidget(
                                    key: const ValueKey("teal"),
                                    value: permittedDays(holidays),
                                    textStyle: ThemeText.centerTextTeal,
                                  )`

**Comment by mingsnx** [comment]
Sorry, can you tell me how to reproduce it, I can't reproduce the problem with the code above.

**Comment by leecasey** [comment]
sometimes it happens sometimes it doesn't. I'm not sure how to tell you how to reproduce it as its quite random. I see no pattern on when it happens. 

          Column(
            children: [
              const Text(
                'Random Number',
                style: TextStyle(),
              ),
              AnimatedDigitWidget(
                key: const ValueKey("teal"),
                value: randomNumber(),
                textStyle: ThemeText.centerTextTeal,
              )
            ],
          ),

**Comment by mingsnx** [comment]
I'm sorry, it's been a long time, but I still can't reproduce it, maybe it's a font problem? Try the latest package and see, I will close the question first, if you still have new phenomena, you can open it again
![image](https://github.com/mingsnx/animated_digit/assets/39380183/2ce9596c-1d3f-4b6d-9e96-dd919a54753c)
```dart
Column(
  children: [
    const Text(
      '{Random Number}',
      style: TextStyle(
        fontSize: 30,
        fontWeight: FontWeight.bold,
        color: Colors.blueAccent,
        fontFamily: "momofont",
      ),
    ),
    AnimatedDigitWidget(
      key: const ValueKey("teal"),
      value: Random().nextInt(DateTime.now().year),
      textStyle: TextStyle(
        fontSize: 100,
        fontWeight: FontWeight.bold,
        color: Colors.blueAccent,
        fontFamily: "momofont",
      ),
    )
  ],
),
```
